### ISSUE TITLE
Media: Poster image not rendering in safari

### ISSUE THREAD

**Issue by spacedmonkey** [google/web-stories-wp#9970] opened 2021-12-13 14:16 UTC
## Bug Description

While viewing the media library in safari, video in the media library do not render a poster. However, there is a image tag with a valid poster src and a poster attribute on the video tag, neither of which render. 

## Screenshots
<img width="1904" alt="Screenshot 2021-12-13 at 14 11 31" src="https://user-images.githubusercontent.com/237508/145828110-ff053861-250b-4ac9-b20a-1747ccf901e6.png">

## Additional Context

- Plugin Version: 1.15.1
- WordPress Version: 5.8
- Operating System:  Mac OS 11.6
- Browser: Safari 15.1

**Comment by swissspidy** [comment] 2021-12-13 15:02
Duplicate of #8449

**Closed as completed by swissspidy** 2021-12-13 15:02 UTC
Labels: Type: Bug, Status: Duplicate, Group: Media, Group: Library
